<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=550 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Семинар 6. Основы библиотеки PyTorch </b></h2>


<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Этот ноутбук посвящён основам  библиотеки PyTorch.

<h3 style="text-align: center;"><b>Введение</b></h3>

В настоящее время существует множество фреймворков глубокого обучения. Разница между ними заключается во внутренних принципах вычислений. Например, в **[Caffe](http://caffe.berkeleyvision.org/)** и **[Caffe2](https://caffe2.ai/)** вы пишете код, используя некоторые «готовые блоки» "(как и $ LEGO ^ {TM} $ :). В **[TensorFlow](https://www.tensorflow.org/)** и **[Theano](http://deeplearning.net/software/theano/)** вы сначала объявляете граф вычислений, затем компилируйте его и используйте для вывода / обучения (`tf.session ()`). Кстати, теперь в TensorFlow (начиная с версии 1.10) есть функция [Eager Execution](https://www.tensorflow.org/guide/eager), которая может быть полезна для быстрого прототипирования и отладки. **[Keras](https://keras.io/)** - очень популярный и полезный фреймворк DL, который позволяет быстро реализовывать нейронный сети и имеет множество полезных функций.


<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

Мы будем использовать **PyTorch**, поскольку он активно развивается и поддерживается AI-сообществом 

<h3 style="text-align: center;"><b>Установка</b></h3>

Подробную инструкцию по установке PyTorch вы можете найти на [официальном сайте PyTorch](https://pytorch.org/).

## Синтаксис Фреймворка

In [2]:
import torch

Несколько фактов о PyTorch:
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для быстрого прототипирования нейронных сетей
- даже быстрее, чем TensorFlow на некоторых задачах
- позволяет легко использовать **GPU**

По своей сути PyTorch предоставляет две основные функции:

- n-мерный тензор, похожий на **numpy**, но может работать на графических процессорах
- Автоматическая дифференциация для построения и обучения нейронных сетей

Если бы PyTorch был формулой, она была бы такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Давайте посмотрим, как мы можем использовать PyTorch для работы с векторами и тензорами.

Напомним, что **тензор** - это многомерный вектор, например :

`x = np.array ([1,2,3])` - вектор = тензор с 1 размерностью (точнее: `(3,)`)

`y = np.array ([[1, 2, 3], [4, 5, 6]])` - матрица = тензор с двумя измерениями (`(2, 3)` в данном случае)

`z = np.array ([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) `-" куб "(3, 3, 3) = тензор с тремя измерениями (` ( 3, 3, 3) `в этом случае)


Одним из реальных примеров трехмерного тензора является **изображение**, оно имеет 3 измерения: `высота`, `ширина` и `глубина канала` (глубина канала = 3 для цветных изображений, 1 для оттенков серого). Вы можете думать об этом как о параллелепипеде, состоящем из действительных чисел.


### Типы Тензоров

В PyTorch мы будем использовать `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) для всех вычислений.

Все типы:

In [3]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

Мы будем использовать только `torch.FloatTensor()` и `torch.IntTensor()`.

Начнем уже что-нибудь писать!

### Создание тензора

In [4]:
a = torch.FloatTensor([1, 2])
a


tensor([1., 2.])

In [5]:
a.shape

torch.Size([2])

In [6]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
b.shape

torch.Size([2, 3])

In [8]:
x = torch.FloatTensor(2,3,4)

In [9]:
x

tensor([[[8.4490e-39, 1.0102e-38, 9.0919e-39, 1.0102e-38],
         [8.9082e-39, 8.4489e-39, 9.6429e-39, 8.4490e-39],
         [9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39]],

        [[8.9082e-39, 9.2755e-39, 8.4490e-39, 1.0194e-38],
         [9.0919e-39, 8.4490e-39, 1.1020e-38, 1.0286e-38],
         [1.0561e-38, 9.2755e-39, 8.4490e-39, 1.0286e-38]]])

In [10]:
x = torch.FloatTensor(100)
x

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.6317e+27,
        2.6302e+20, 6.1943e-04, 5.1492e+31, 2.2234e-10, 1.7033e+25, 1.5766e-19,
        1.7753e+28, 1.3458e-14, 5.2299e-05, 1.7186e-04, 4.0372e-08, 2.3308e-09,
        6.4461e-10, 4.0372e-08, 1.5275e-04, 2.6948e-09, 4.0372e-08, 2.3308e-09,
        6.4461e-10, 4.0372e-08, 1.9406e+17, 1.3563e-19, 1.3563e-19, 5.2244e-05,
        4.2015e-05, 4.0372e-08, 3.8188e-05, 4.2964e-05, 4.0372e-08, 1.5275e-04,
        1.0490e-08, 4.0372e-08, 3.8188e-05, 1.7186e-04, 4.0372e-08, 1.9406e+17,
        1.3563e-19, 1.3563e-19, 2.0897e-04, 1.0490e-08, 4.0372e-08, 1.5275e-04,
        6.8246e-07, 4.0372e-08, 2.3308e-09, 4.2483e-05, 4.0372e-08, 1.5275e-04,
        2.6948e-09, 4.0372e-08, 3.1458e-12, 1.7055e+28, 1.3563e-19, 1.3563e-19,
        4.1918e-11, 1.0721e-08, 1.7088e-04, 4.2093e-11, 6.7508e-07, 1.7088e-04,
        4.1865e-11, 6.7377e-10, 1.7088e-04, 4.0274e-11, 1.7247e-07, 4.2719e-05,
        1.7035e+28, 1.3563e-19, 1.3563e-

In [11]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Примечание:** если вы создаете `torch.Tensor` с помощью следующего конструктора, он будет заполнен мусором из "случайных номеров":

In [12]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[         0,          0,          0,          0],
         [         7,          0,          8,          0]],

        [[1065353216,          0, -852817408,        441],
         [         1,          0,          0,          0]],

        [[         0,          0,          0,          0],
         [         7,          0,          8,          0]]], dtype=torch.int32)

### Инициализации тензоров

In [13]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)

Инициализация случайного распределения

In [14]:
x = torch.randn((2,3))                # Normal(0, 1) с размером (2, 3)
x

tensor([[ 0.1330,  0.2846,  2.3294],
        [-1.1127, -1.4203,  0.1701]])

In [15]:
x.random_(0, 10)                      # Дискретное равномерно U[0, 10]
x.uniform_(0, 1)                      # Равномерно U[0, 1]
x.normal_(mean=0, std=1)              # Нормальное со средним 0 и дисперсией 1
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

tensor([[1., 1., 1.],
        [0., 1., 0.]])

## Функции в Torch 

У всех функций Numpy есть своя пара в Torch! Осталось теперь вспомнить numpy 🙂

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

### Изменение формы
`np.reshape()` == `torch.view()`:

In [16]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
b.view(3, 2).shape

torch.Size([3, 2])

In [18]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 (3, 1))

In [20]:
b.view(3, 2), b.view(3, 2).stride()  

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 (2, 1))

**Примечание:** `torch.view ()` создает новый тензор, но старый остается неизменным

In [21]:
b.view(-1, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [22]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
b.T.stride(), b.is_contiguous(), b.T.is_contiguous()

((1, 3), True, False)

<img src='https://lh3.googleusercontent.com/proxy/pbQ8C9YLVguU2LzlfE2-57lC3KK3yIRsQnpaTOK9S2UPpopvnZ3JhgeMcT6_kqYL56xq18ZFqddzPhszZg1W9YY--y-qDD2-bJrjVYivMdpQgRqiumwh6PpJYU3cL5Mua9RNeVp6xK0'>

In [24]:
b.reshape(-1) # возвращает view или contigues тензор

tensor([1., 2., 3., 4., 5., 6.])

In [25]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Изменение типа тензора

In [26]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [27]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [28]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [29]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [30]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [31]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [32]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [33]:
a[0, 0]

tensor(100.)

In [34]:
a[0:2, 1]

tensor([ 20., 163.])

### Арифметические операции

| операция | аналоги |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

#### Сложение

In [35]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [36]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [37]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [38]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [39]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

#### Вычитание

In [40]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [41]:
a.sub(b) # copy

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [42]:
a.sub_(b) # inplace

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

#### Умножение (поэлементное)

In [43]:
a * b

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

In [44]:
a.mul(b)

tensor([[-2.0000e+00, -8.0000e+00, -1.8000e+01],
        [-2.0000e+02, -8.0000e+02, -1.8000e+03],
        [-2.0000e+04, -8.0000e+04, -1.8000e+05]])

#### Деление (поэлементное):

In [45]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [46]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [47]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Примечание:** все эти операции создают новые тензоры, старые тензоры остаются неизменными.

In [48]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [49]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

### Операторы сравнения

In [50]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [51]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [52]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [53]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [54]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

### Использование индексации по логической маске

In [55]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [56]:
b[a == b]

tensor([100., 200., 300.])

### Поэлементное применение **универсальных функций**

In [57]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [58]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [59]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [60]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [61]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [62]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [63]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [64]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

### Агрегация и работа с осями
#### sum, mean, max, min:

In [65]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [66]:
a.mean()

tensor(74.)

#### Применение функции вдоль оси

In [67]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [68]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [69]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [70]:
a.max()

tensor(300.)

In [71]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

**Примечание:** второй тензор, возвращаемый `.max()`, содержит индексы элементов max вдоль этой оси. Например. в этом случае `a.max ()` вернула `(100, 200, 300)`, которые являются минимальными элементами по оси 0 (вдоль столбцов), а их индексы по оси 0 равны `(2, 2, 2)`.


#### Фиктивные оси

Иногда очень сложно бывает разобраться, как правильно выбрать оси для применения операций с многомерными массивами. Поэтому сейчас мы решим на эту тему пару задач.
Сначала посмотрим, как создавать у массивов новые фиктивные оси, это нам пригодится.

In [72]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

a[:, None, :].shape

torch.Size([3, 1, 3])

In [73]:
a[:, :, None]

tensor([[[  1.],
         [  2.],
         [  3.]],

        [[ 10.],
         [ 20.],
         [ 30.]],

        [[100.],
         [200.],
         [300.]]])

#### Безобидная задача на кумулятивные суммы
Дана матрица $M \times N$. Напишите функцию, которая возвращает вектор средних значений по вертикали. 



In [74]:
def vertical_means(A):
    """
    param A: torch.tensor[m,n]
    """

    result = A.mean(dim=0)

    return result # <YOUR CODE>

A = torch.FloatTensor([[1, 4], 
                       [2, 7]] )

vertical_means(A)

tensor([1.5000, 5.5000])

**Проблемы:**

* Что такое вертикальная ось? 
* По какой оси необходимо суммировать?
* Как не ошибиться?

**Ответ:** Операции всегда производятся по той оси, которая **исчезнет** после применения операции.

#### Задача на нормализацию изображения
Реализуйте функцию ``normalize_pictures(A)``, которая принимает на вход четырёхмерный тензор --- батч из ``batch_size`` изображений, каждое из которых является трехмерным тензором формы (num_channels, width, height). Нужно стандартизировать изображение по каждому каналу, то есть сделать так, чтобы среднее значение яркости каждого канала (по всем изображениям и всем пикселям) было равно 0, а стандартное отклонение --- 1.

In [75]:
def normalize_pictures(A):
    """
    param A: torch.Tensor[batch_size, num_channels, width, height]
    """

    m = A.mean(dim=(2,3))
    sigma = A.std(dim =(2, 3))

    result = (A - m[:, :, None, None])/sigma[:, :, None, None]


    return result

In [76]:
batch = torch.randint(0, 156, (64, 3, 300, 300), dtype=torch.float32)
batch.mean(dim=(2,3)).shape

torch.Size([64, 3])

In [77]:
batch = torch.randint(0, 256, (64, 3, 300, 300), dtype=torch.float32)

B = normalize_pictures(batch)
# print(B.mean(dim=(2,3)).shape)
# print(B.std(dim=(2,3)))

## Матричные операции

#### Транспонирование тензора

In [78]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [79]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

Это тоже не inplace-операция:

In [80]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

#### Скалярное произведение векторов

In [81]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [82]:
a.dot(b)

tensor(-141.)

In [83]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [84]:
a @ b

tensor(-141.)

In [85]:
type(a)

torch.Tensor

In [86]:
type(b)

torch.Tensor

In [87]:
type(a @ b)

torch.Tensor

#### Матричное произведение

In [88]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [89]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [90]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [91]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [92]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [93]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

Тензор `b` можно развернуть в одномерный массив с помощью функции `torch.view(-1)`, чтобы результат был вектором

In [94]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [95]:
b.view(-1)

tensor([ -1., -10., 100.])

In [96]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [97]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [98]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

## Конвертация
#### Конвертация из Numpy в Pytorch:

In [99]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.75393635, 0.23748027, 0.23200792],
       [0.36955589, 0.77629554, 0.33796111],
       [0.33959749, 0.37064881, 0.40360936]])

In [100]:
b = torch.from_numpy(a)
b

tensor([[0.7539, 0.2375, 0.2320],
        [0.3696, 0.7763, 0.3380],
        [0.3396, 0.3706, 0.4036]], dtype=torch.float64)

**Внимание!** `a` и `b` хранятся в одной и той же ячейке данных. Если именить один тензор, то изменится и другой.

In [101]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [102]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Конвертация из Torch в Numpy

In [103]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[0.0000e+00, 1.0102e-38, 7.0295e+28, 6.1949e-04],
         [1.9070e-19, 7.5553e+28, 5.2839e-11, 2.7604e+20],
         [1.7744e+28, 1.3458e-14, 2.5204e-12, 1.4586e-19]],

        [[1.4600e-19, 2.5039e-12, 2.5039e-12, 7.9353e+17],
         [3.1887e-09, 1.4585e-19, 2.5038e-12, 6.4101e-10],
         [1.9069e+17, 2.7481e+20, 1.4588e-19, 7.0374e+22]]])

In [104]:
type(a)

torch.Tensor

In [105]:
x = a.numpy()
x

array([[[0.0000000e+00, 1.0102041e-38, 7.0294782e+28, 6.1949180e-04],
        [1.9069532e-19, 7.5553316e+28, 5.2839018e-11, 2.7603586e+20],
        [1.7743541e+28, 1.3457865e-14, 2.5203925e-12, 1.4585552e-19]],

       [[1.4599804e-19, 2.5038502e-12, 2.5038929e-12, 7.9353293e+17],
        [3.1886982e-09, 1.4584911e-19, 2.5037858e-12, 6.4101080e-10],
        [1.9068770e+17, 2.7481158e+20, 1.4588275e-19, 7.0373527e+22]]],
      dtype=float32)

In [106]:
x.shape

(2, 3, 4)

In [107]:
type(x)

numpy.ndarray

In [108]:
x -= x

In [109]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

#### Задание. Реализация функции forward
Реализуйте функцию `forward_pass(X, w)` для одного нейрона нейронной сети с активацией ``sigmoid``. Используйте библиотеку PyTorch

<img src='https://radioprog.ru/uploads/media/articles/0001/05/267ad35a9e64a7b92c2e3b94940f686816ea6bf8.jpeg'>

In [110]:
def forward_pass(X, w):

  logits = X @ w
  result  = torch.sigmoid(logits)

  return result


  


In [111]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
print(X.shape)
w = torch.FloatTensor([[-0.5], [2.5]])
print(w.shape)
result = forward_pass(X, w)
print('result: {}'.format(result))

torch.Size([3, 2])
torch.Size([2, 1])
result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


## <h1 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

CUDA --- это программно-аппаратная архитектура параллельных вычислений, которая позволяет существенно увеличить вычислительную производительность благодаря использованию графических процессоров фирмы Nvidia. Для нас CUDA --- это драйвер, который позволяет нам проводить вычисления на GPU.

[CUDA documentation](https://docs.nvidia.com/cuda/)

Для вычислений на Pytorch мы можем использовать как CPU (Central Processing Unit), так и GPU (Graphical Processing Unit). Между ними можно легко переключаться, и это очень важно!

In [112]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.5342, 0.9961, 0.9538,  ..., 0.9616, 0.4175, 0.8085],
        [0.8566, 0.4115, 0.3657,  ..., 0.9194, 0.1597, 0.3664],
        [0.4005, 0.8570, 0.6270,  ..., 0.4526, 0.9736, 0.3983],
        ...,
        [0.4368, 0.8593, 0.6167,  ..., 0.8957, 0.8163, 0.4143],
        [0.8980, 0.5288, 0.6334,  ..., 0.9913, 0.1481, 0.5196],
        [0.9741, 0.2409, 0.5722,  ..., 0.8575, 0.9809, 0.5747]])

In [113]:
x.is_cuda

False

#### Кладём тензор на GPU

In [115]:
!nvidia-smi

Mon Apr  3 22:39:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:07:00.0  On |                  N/A |
| 49%   38C    P0    33W / 170W |   1126MiB /  6144MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [116]:
x = x.cuda()

In [117]:
!nvidia-smi

Mon Apr  3 22:40:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:07:00.0  On |                  N/A |
| 48%   39C    P0    34W / 170W |   1260MiB /  6144MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [118]:
x

tensor([[0.5342, 0.9961, 0.9538,  ..., 0.9616, 0.4175, 0.8085],
        [0.8566, 0.4115, 0.3657,  ..., 0.9194, 0.1597, 0.3664],
        [0.4005, 0.8570, 0.6270,  ..., 0.4526, 0.9736, 0.3983],
        ...,
        [0.4368, 0.8593, 0.6167,  ..., 0.8957, 0.8163, 0.4143],
        [0.8980, 0.5288, 0.6334,  ..., 0.9913, 0.1481, 0.5196],
        [0.9741, 0.2409, 0.5722,  ..., 0.8575, 0.9809, 0.5747]],
       device='cuda:0')

In [119]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Mon Apr  3 22:40:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.98       Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:07:00.0  On |                  N/A |
| 48%   39C    P0    34W / 170W |   1280MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [120]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

x = x.to(device)
x

tensor([[0.5342, 0.9961, 0.9538,  ..., 0.9616, 0.4175, 0.8085],
        [0.8566, 0.4115, 0.3657,  ..., 0.9194, 0.1597, 0.3664],
        [0.4005, 0.8570, 0.6270,  ..., 0.4526, 0.9736, 0.3983],
        ...,
        [0.4368, 0.8593, 0.6167,  ..., 0.8957, 0.8163, 0.4143],
        [0.8980, 0.5288, 0.6334,  ..., 0.9913, 0.1481, 0.5196],
        [0.9741, 0.2409, 0.5722,  ..., 0.8575, 0.9809, 0.5747]],
       device='cuda:0')

Умножим два тензора в GPU и вернём результат обратно на CPU:

In [121]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [122]:
c

tensor([[0.1360, 0.4289, 0.0300,  ..., 0.0252, 0.2180, 0.3195],
        [0.2326, 0.7066, 0.0563,  ..., 0.3022, 0.6476, 0.0743],
        [0.5468, 0.0162, 0.3418,  ..., 0.7377, 0.0308, 0.6880],
        ...,
        [0.3123, 0.0436, 0.4298,  ..., 0.0767, 0.0051, 0.6317],
        [0.7565, 0.0743, 0.3140,  ..., 0.0842, 0.0066, 0.8445],
        [0.4173, 0.7197, 0.5612,  ..., 0.3683, 0.3335, 0.1433]])

In [123]:
a

tensor([[0.1872, 0.9280, 0.4760,  ..., 0.2160, 0.4737, 0.4159],
        [0.7066, 0.9350, 0.2063,  ..., 0.4400, 0.6666, 0.4303],
        [0.8629, 0.1068, 0.5204,  ..., 0.9463, 0.3243, 0.9546],
        ...,
        [0.9635, 0.1073, 0.9677,  ..., 0.1501, 0.0088, 0.9786],
        [0.9110, 0.8418, 0.9096,  ..., 0.2180, 0.6679, 0.8614],
        [0.4643, 0.7999, 0.8121,  ..., 0.6052, 0.4997, 0.5181]])

Тензоры из разных областей памяти не совместимы:

In [124]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [125]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Пример работы на GPU

In [126]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [127]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# проверить наличие CUDA (NVIDIA GPU)
if torch.cuda.is_available():
    # получить имя устройства CUDA
    device = torch.device('cuda')          # Объект CUDA-устройства
    y = torch.ones_like(x, device=device)  # создаем тензор на GPU
    x = x.to(device)                       # или просто `.to("cuda")`
    z = x + y
    print(z)
    # вы можете установить тип во время операции `.to`
    print(z.to("cpu", torch.double))

tensor([[[1.2871, 1.8004, 1.5683, 1.0440, 1.0809],
         [1.7763, 1.5514, 1.3354, 1.8435, 1.2765],
         [1.4997, 1.3453, 1.5922, 1.5623, 1.0924],
         [1.2173, 1.5340, 1.4585, 1.2305, 1.1598],
         [1.3621, 1.2946, 1.1913, 1.2636, 1.0825]],

        [[1.6193, 1.3109, 1.7225, 1.6621, 1.4144],
         [1.8331, 1.4365, 1.0079, 1.5320, 1.0807],
         [1.5574, 1.7712, 1.7061, 1.4191, 1.8846],
         [1.9415, 1.6780, 1.1633, 1.9384, 1.6735],
         [1.5652, 1.6539, 1.3869, 1.4006, 1.0298]],

        [[1.7687, 1.2344, 1.9505, 1.3898, 1.5982],
         [1.6159, 1.8375, 1.6295, 1.2128, 1.0117],
         [1.5774, 1.5474, 1.4158, 1.6299, 1.5038],
         [1.8913, 1.8173, 1.0846, 1.4090, 1.0394],
         [1.0445, 1.8599, 1.1771, 1.7403, 1.9594]],

        [[1.2234, 1.4752, 1.6427, 1.0325, 1.0997],
         [1.8471, 1.3128, 1.7788, 1.1962, 1.2985],
         [1.6756, 1.3777, 1.7624, 1.5396, 1.3262],
         [1.7731, 1.5440, 1.1468, 1.6500, 1.0009],
         [1.0557, 1.3673,

## AutoGrad

За что мы любим PyTorch --- за то, что в нём можно автоматически дифференцировать функции! Об этом можно было бы только мечтать в Numpy. Дифференцирование функций происходит по формуле производной композиции.

**Правило производной композиции (a.k.a. backpropagation)**

Пусть есть функция $f(w(\theta))$. Вычислим её производную:
$${\frac  {\partial{f}}{\partial{\theta}}}
={\frac  {\partial{f}}{\partial{w}}}\cdot {\frac  {\partial{w}}{\partial{\theta}}}$$


*Как рассказывалось на лекции, в многомерном случае можно записать аналог этой формулы:*
$$
D_\theta(f\circ w) = D_{w(\theta)}(f)\circ D_\theta(w)
$$

Простой пример обратного распространения градиента:

$$y = \sin \left(x_2^2(x_1 + x_2)\right)$$

<img src="https://ars.els-cdn.com/content/image/1-s2.0-S0010465515004099-gr1.jpg" width=700></img>


Autograd позволяет производить автоматическое дифференцирование для всех операций на тензорах. Граф вычислений, в отличие от Tensorflow, строится динамически. Давайте посмотрим, как это работает.

#### Задание. Реализуйте обучение в логистической регрессии

In [128]:
# Разберем пример: применим линейную регрессию цен на жилье в Бостоне.

In [131]:
import matplotlib.pyplot as plt
import torch
%matplotlib inline

from sklearn.datasets import load_boston
boston = load_boston()
plt.scatter(boston.data[:, -1], boston.target)

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [132]:
w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

x = torch.tensor(boston.data[:, -1] / 10, dtype=torch.float32)
y = torch.tensor(boston.target, dtype=torch.float32)

NameError: name 'boston' is not defined

In [133]:
y_pred = w * x + b
loss = torch.mean((y_pred - y)**2)

# propagete gradients
loss.backward()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [134]:
print("dL/dw = \n", w.grad)
print("dL/db = \n", b.grad)

dL/dw = 
 None
dL/db = 
 None


In [135]:
from IPython.display import clear_output

for i in range(100):

    y_pred = w * x + b

    # Вычисляем функцию ошибок
    loss = torch.mean((y_pred - y)**2)

    # Вычисляем градиенты
    loss.backward()


    # Делаем шаг градиентного спуска по матрице весов
    w.data -= 0.05*w.grad.data
    b.data -= 0.05*b.grad.data

    # обнуляем градиенты
    w.grad.data.zero_()
    b.grad.data.zero_()



    # the rest of code is just bells and whistles
    if (i+1) % 5 == 0:
        clear_output(True)
        plt.scatter(x.data.numpy(), y.data.numpy())
        plt.scatter(x.data.numpy(), y_pred.data.numpy(),
                    color='orange', linewidth=5)
        plt.show()

        print("loss = ", loss.data.numpy())
        if loss.data.numpy() < 0.5:
            print("Done!")
            break

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Посмотрим градиенты на примере двухслойной сети

In [136]:
dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Раскомментируйте это, чтобы запустить на GPU

# N - размер батча; D_in - входной размер;
# H - размер скрытого слоя; D_out - размер вывода.
N, D_in, H, D_out = 64, 3, 3, 10
N, D_in, H, D_out = 64, 3, 3, 10

# Создание случайных тензоров для хранения входных и выходных данных.
# Настройка requires_grad = False указывает, что нам не нужно вычислять градиенты
# по отношению к этим тензорам во время обратного прохода.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Создаем тензоры случайных весов.
# Настройка requires_grad = True указывает, что мы хотим вычислять градиенты с
# уважение к этим тензорам во время обратного прохода.

# Create random Tensors for weights.
# Установка requires_grad = True указывает, что мы хотим вычислить градиенты 
# относительно этих тензоров во время обратного прохода.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

In [137]:
y_pred = (x @ w1).clamp(min=0).matmul(w2)
loss = (y_pred - y).pow(2).sum()

# вычисляем градиенты
loss.backward()

In [138]:
print((y_pred - y).pow(2).sum())

tensor(4784.5840, grad_fn=<SumBackward0>)


In [139]:
w1.grad, w2.grad

(tensor([[-585.0563,  201.9738,  -22.3251],
         [-411.6076, 1461.3861, -231.7098],
         [ 835.8212, 1539.8296, -302.2103]]),
 tensor([[  162.4768,    68.2247,  -320.5003,   120.0310,   275.5796,     3.2287,
            -74.5451,  -227.1323,    62.3513,  -259.3231],
         [  999.4940,  -548.8942,  -991.7618,   347.7159,  -254.5562,   840.0114,
           -340.1570, -1522.5104,   407.5187, -1427.7157],
         [   94.0916,   -25.5721,  -132.8701,    36.1702,    49.7349,    60.5954,
            -23.5204,  -162.8555,    56.2052,  -144.7920]]))

In [140]:
loss.grad # нет доступа к нелистовым градиентам в дереве AD

C:\Users\Alex\AppData\Local\Temp\ipykernel_18604\1930231510.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:491.)
  loss.grad # нет доступа к нелистовым градиентам в дереве AD


In [141]:
# заставляем переменную запоминать градиенты фнукции потерь
y_pred = (x @ w1).clamp(min=0).matmul(w2)
y_pred.retain_grad()

loss = (y_pred - y).pow(2).sum()
loss.retain_grad()

loss.backward()

In [142]:
loss.grad

tensor(1.)

In [143]:
x.grad # не требует градиента

In [144]:
y.grad # не требует градиента

**Замечание:** Градиенты помещаются в поле `.grad` тензоров, на которых они вычисляются.

In [145]:
w1

tensor([[-1.0101,  1.2878, -0.5344],
        [-1.2513,  2.6790,  0.2900],
        [ 0.5130,  1.8148,  0.1160]], requires_grad=True)

In [146]:
with torch.no_grad():
  
    pass

## Дополнительные материалы

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*